### ISSUE TITLE
Missing Files?

### ISSUE THREAD

**Issue by kestrel1110** [toilethinges/Adamas-Project#3]
So I am looking at the mission for opening the dust wormhole in Pulvis. And there is no Pulvis in the files. Is there something missing?

**Comment by toilethinges** [comment]
The events for the Dust Wormhole in Pulvis are left over from the old system names and the first few missions I made before they were removed. So the system got renamed and the missions referencing it were in a now-nonexistent file. Currently, the only mission in the plugin is the First Contact mission.

**Comment by kestrel1110** [comment]
Is there a way I can have those old files?

**Comment by kestrel1110** [comment]
If not, I have a version that is going to be pr'ed soon, with a lot more missions and events. I also fixed a bug or two. And lastly, is there a site where I can get the blender files for all the ships? Like Google drive? If so, I would love to get some thumbnails in...

**Comment by toilethinges** [comment]
No, old files are gone. I do still have most the assets if you want to add me on Steam or Discord, I'll send them to you.

(You should be able to find me pretty easily on Steam, or on the Endless Sky Discord.)

**Comment by toilethinges** [comment]
I sent you a friend request on Discord, I think anything else is outside the scope of this issue. :)
